name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: yousufkalim/eslint-action@v1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: "--ignore-path=.gitignore"
          extensions: "js,jsx,ts,tsx"
          annotations: true
